version: "3.9"

services:
  hailstonehacker:
    build: .
    ports:
      - 13338:9999
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "13338"]
      interval: 1m00s
      timeout: 10s
      retries: 3
      start_period: 60s